import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

class UnkownLexicalUnitException extends Exception {
    public UnkownLexicalUnitException(String message) {
        super(message);
    }
}

public class Main {
    public static void main(String args[]) {

        if (args.length == 0) {
            System.err.println("Usage: java -jar part1.jar <filename>");
            System.exit(1);
        }

        ArrayList<Symbol> variables = new ArrayList<Symbol>();
        LexicalAnalyzer lexicalAnalyzer;
        String filename = args[0];

        try {

            lexicalAnalyzer = new LexicalAnalyzer(new FileReader(filename));
            

            Symbol symbol;
            do {
                symbol = lexicalAnalyzer.nextSymbol();
                System.out.println(symbol.toString());

                if (symbol.getType() == LexicalUnit.VARNAME && !containsValue(symbol.getValue(), variables)) {
                    variables.add(symbol);
                }

            } while (symbol.getType() != LexicalUnit.END);

            System.out.println("Variables");
            sort(variables);

        } catch (FileNotFoundException e) {
            // Exception for the FileReader().
            e.printStackTrace();
        } catch (IOException e) {
            // Thrown by the Lexer generated by JFlex.
            e.printStackTrace();
        } catch (UnkownLexicalUnitException e) {
            // Thrown by us if an unknwon lexical unit is seen.
            System.err.println(e.getMessage());
        }
    }

    public static void sort(ArrayList<Symbol> variables) {
        variables.sort(Comparator.comparing(
                
                var -> var.getValue().toString().toLowerCase()));

        for (Symbol var : variables) {
            System.out.println(var.getValue() + " " + var.getLine());
        }

    }

    public static boolean containsValue(Object value, ArrayList<Symbol> symbolsList) {
        for (Symbol var : symbolsList) {
            // TODO :Null pointer à vérifier
            if (value.equals(var.getValue())) {
                return true;
            }
        }
        return false;
    }

}
